name: arbchar
description: Bluetooth chat app (Arbchar)
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.5.5
  permission_handler: ^10.2.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  encrypt: ^5.0.3
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
